spring:
  application:
    name: rest-library-API-with-spring-boot

    #Configuração do Banco de dados:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #Classe do driver JDBC para conectar com o MySQL
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    #Configurações do JPA:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect #dialeto do SQL utilizado pelo JPA
    #Configurações do Hibernate:
    hibernate:
      ddl-auto: update
    properties: #Propriedades específicas do Hibernate
      hibernate:
    show-sql: true #Exibe no console os comandos SQL gerados pelo hibernate - true é util para debug

logging:
  level:
    com.github.tiagoribeine: INFO